// <auto-generated />
namespace Dont_Panic_MVC_API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class jobfixed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(jobfixed));
        
        string IMigrationMetadata.Id
        {
            get { return "201402102344116_jobfixed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
